source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'mysql2', '~> 0.3.20'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

gem 'twitter-bootstrap-rails'

# Simplified Form Management
gem 'simple_form'
# Authentication Support
gem 'devise'
gem 'devise-bootstrap-views'
# Admin Section Support
gem 'rails_admin'
