default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: restapp-clase3_development

test:
  <<: *default
  database: restapp-clase3_test

production:
  <<: *default
  database: restapp-clase3_production
  username: restapp-clase3
  password: <%= ENV['RESTAPP-SPRINT1_DATABASE_PASSWORD'] %>
